# Generated by Django 3.2.19 on 2023-05-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_alter_smartphones_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphones',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
