# Generated by Django 3.2.19 on 2023-05-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_smartphones_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphones',
            name='tags',
            field=models.CharField(default=[], max_length=1000),
        ),
    ]
