# Generated by Django 3.2.19 on 2023-05-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0005_alter_smartphones_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphones',
            name='tags',
            field=models.CharField(default=(), max_length=1000),
        ),
    ]
