# Generated by Django 3.2.19 on 2023-06-05 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0010_smartphones_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphones',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main_site.category'),
        ),
    ]
